### ISSUE TITLE
Migrating from jetstack to tremolosecurity failed

### ISSUE THREAD

**Issue by phr0zenx** [TremoloSecurity/kube-oidc-proxy#13]
I'm using the helm chart from tremolo's kube-oidc-proxy branch:
https://github.com/TremoloSecurity/kube-oidc-proxy/tree/master/deploy/charts/kube-oidc-proxy
Need your advice on what i'm missing?

Forwarded from following url:
https://www.reddit.com/r/kubernetes/comments/rvxqjt/updating_kubeoidcproxy/

Encountered following error:

```
I0113 11:30:21.271756 7640 round_trippers.go:570] HTTP Statistics: GetConnection 0 ms ServerProcessing 24 ms Duration 32 ms
I0113 11:30:21.271756 7640 round_trippers.go:577] Response Headers:
I0113 11:30:21.272732 7640 round_trippers.go:580] Date: Thu, 13 Jan 2022 03:30:21 GMT
I0113 11:30:21.273728 7640 round_trippers.go:580] Content-Type: text/html
I0113 11:30:21.274723 7640 round_trippers.go:580] Content-Length: 146
I0113 11:30:21.275720 7640 round_trippers.go:580] Strict-Transport-Security: max-age=15724800; includeSubDomains
I0113 11:30:21.285723 7640 request.go:1181] Response Body: <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
I0113 11:30:21.288718 7640 request.go:1372] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
I0113 11:30:21.291721 7640 cached_discovery.go:125] skipped caching discovery info, no groups found
```

Using keycloak as our oidc.
Value.yml file for helm deployment as follows (same file can be used to successfully deploy jetstack's helm chart):

```
replicaCount: 1

image:
  repository: quay.io/jetstack/kube-oidc-proxy
  tag: v0.3.0
  pullPolicy: IfNotPresent


oidc:
  clientId: REDACTED
  issuerUrl: https://REDACTED/auth/realms/master
  usernameClaim: email
  usernamePrefix: "oidc:"
  groupsClaim: groups
  groupsPrefix: "oidc:"

  signingAlgs:
    - RS256
  requiredClaims: {}

tokenPassthrough:
  enabled: false
  audiences: []

extraImpersonationHeaders:
  clientIP: true

extraArgs: {}

extraVolumeMounts: {}

extraVolumes: {}

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  hosts:
    - host: REDACTED
      paths:
        - /
  tls:
    - secretName: REDACTED
      hosts:
        - REDACTED

podDisruptionBudget:
  enabled: false
  minAvailable: 1

resources: {}
  
initContainers: []

nodeSelector: {}

tolerations: []

affinity: {}
```

**Comment by mlbiam** [comment]
Sorry, missed a notification.  We didn't spend much time on the helm charts, since our focus is on our integration with openunison's charts. That said, it looks like you are still using the old image

> repository: quay.io/jetstack/kube-oidc-proxy

The new image is `docker.io/tremolosecurity/kube-oidc-proxy:latest`

It looks like the proxy is getting a 404 trying to start. Is the container in a read state?

**Comment by kingdonb** [comment]
I tried to drop in the latest image on my cluster, which was also running the old jetstack kube-oidc-proxy from a Helm chart (that has been upgraded slightly) and got these errors preventing startup:

```
Error: Failed to read the CA contents: data does not contain any valid RSA or ECDSA certificates

[... the help text]
```

**Comment by kingdonb** [comment]
I got the impression that OpenUnison and kube-oidc-proxy are meant to be used together. I might be missing something because I see the blog post suggests setting these values:

```
impersonation:
  use_jetstack: true
  jetstack_oidc_proxy_image: docker.io/tremolosecurity/kube-oidc-proxy:latest
  explicit_certificate_trust: true
```

but since I'm not using OpenUnison, these do not appear to be values that I can set.

Is there an entrypoint for using the updated kube-oidc-proxy with another OIDC provider? I've been using Keycloak and kube-oidc-provider together. I found a section in the docs that mentions keycloak, but I am not sure what OpenUnison provides at large and I get the sense that I have to read more docs and take in the full product to understand better.

I was really hoping for a way to drop-in an updated kube-oidc-proxy and keep on moving, I'll read more docs since there's bound to be something important I've missed by skipping over so much. I don't want to minimize any of the work you've done by suggesting "you should do what I need instead" but if this is a common use case, it would be really helpful to have a document that is oriented towards migrating to OpenUnison, from Keycloak, or with an existing Keycloak installation.

I'll be very happy to be pointed at any existing docs that might help me get moving in the right direction!
